<?php

/**
 * @file
 * Contains transaction.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function transaction_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the transaction module.
    case 'help.page.transaction':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Transactions entity') . '</p>';
      return $output;

    default:
  }
}
